# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Maps' do
  #ne if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Maps
  pod 'KVNProgress'
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'
  
end
